### 4 Python Homework

---

## Questions

1. What does one need to do to use a module?
    - We need to import the respective module into our code base

2. Name a Module (not the DateTime Nodule) we looked at and write a line or 2 of code as an example using this module.

    - Math Library
        - import math
        - print("Absoulte Value...", math.fabs(-235.21))

3. What is a benefit of using Exception handling?
    - It helps with anticipating runtime errors. We can use corrective measures to see what may have gone wrong in our code block. It allows code to run even if errors occur.

4. What are the 4 components used for Python Exception Handling?
    - try, except, else, and finally

5. NumPy arrays are like what Python data type?
    - Lists

6. What is one of the main benefits of using NumPy arrays.
    - NumPy uses less memory compared to list

7. What is one of the main requirements about the 'dtype' of NumPy arrays?
    - the data needs to bbe the same type

8. Of the 10 uses of NumPy, name 2.
    - Matrix Operations, and Statistcal Operations

9. Name one of the other libraries we'll use with NumPy?
    - Matplotlib

10. What is the shape of NumPy arrays?
    - A Tuple of non-negative integers that specify the dimensions, length and size of each array (3,2,4)

11. What is a Tensor?
    An array with 3+ dimensions

12. Name a reason why it's better using NumPy for Data Analysis than using a Python List?
    - It adds data structures to Python that guarantee efficient calculations with arrays and matrices

13. When creating an "empty" array, where do the elements come from?
    - It will pull the last used elements 

In [6]:
# Use the DateTime module to get Current Date and Time, and save it to a variable. Then extract just the Full month name form that variable.

import datetime as dt

a = dt.datetime.now()
print("Current date and time...", a)

# Full Month name

print("Current Month...", a.strftime("%B"))


Current date and time... 2023-02-20 11:56:02.087104
Current Month... February


In [12]:
# Write a simple function that takes 2 parameters -- a first name and a day name.

'''
Set a default value for the day name of Sunday.
Have the function print out a greeting -- using the parameters -- that says something like "Hi first-name! Happy day-name!". Remember to use the variables in the greeting to replace first-name and day-name.
Invoke this function with 2 variables.
Invoke this function with 1 variable only.

'''

import datetime as dt

def nd(name, day = "Sunday"):
    print("Hi", name, "Happy", day,"!")
    
nd("Jaunita", "Monday")
nd("Travis")

Hi Jaunita Happy Monday !
Hi Travis Happy Sunday !


In [13]:
# Write a block of code to handle one of the most common Python exception errors. Select one of the common errors from the curriculum section on Python Exception handling. Have your code example uses the try,except, else, and finally components.

try:
    print(f)
except NameError:
    print("F is not defined")
else:
    print("F is defined as...")
finally:
    print("This assignment is finished")



F is not defined
This assignment is finished


In [32]:
# Import NumPy, use one of the NumPy methods and create an array with a shape of ... (2, 3, 2). You can use the reshape method -- .reshape()

import numpy as np

d = np.arange(12).reshape([2,3,2])
print("Array d...", d)






Array d... [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]]


In [33]:
# Use NumPy .linspace() to create an array with 6 linearly spaced values between 0 and 20

import numpy as np

v = np.linspace(0, 20, num=6)
print("Array V...", v)

Array V... [ 0.  4.  8. 12. 16. 20.]


In [34]:
# Make a Deep Copy of the above array you created in point #5 above.
import copy

v = np.linspace(0, 20, num=6)
vcopy = copy.deepcopy(v)

print("Original Array...", v)
print("Copy of Array...", vcopy)

Original Array... [ 0.  4.  8. 12. 16. 20.]
Copy of Array... [ 0.  4.  8. 12. 16. 20.]


In [35]:
# Using NumPy, 'broadcast' the multiplication of the following 2 arrays below to a 2-D array using the newaxis parameter ...

'''
[0.71, 0.1, 0.24, 0.3]
[0.8, 0.59, 1.0, 1.11]
'''
from numpy import array, newaxis

first = array([0.71, 0.1, 0.24, 0.3])
second = array([0.8, 0.59, 1.0, 1.11])

print("First and Second Arrays multiplied...\n")
print(first[:,newaxis] * second)

First and Second Arrays multiplied...

[[0.568  0.4189 0.71   0.7881]
 [0.08   0.059  0.1    0.111 ]
 [0.192  0.1416 0.24   0.2664]
 [0.24   0.177  0.3    0.333 ]]
