### Week 5 Homework

--- 


## Questions

1. What does Pandas stand for?

    - Panal Data

2. What are the 2 collections used in Pandas?

    - Series and Dataframes

3. Name 4 things Pandas can do for us.

    - Data Cleaning, Data Insection, Merges and Joins, Data Visualization

4. To permanently sort a DataFrame, which keyword should one use with the df.sort() method?

    -inplace=true

5. What is a CSV

    - Comma Seperated Value File

6. When cleaning data what values do we not like in our data?
    - Null or zero values




In [ ]:
# Concatenate these 3 arrays into a new array named 'newArray'...
import numpy as np

d1 = np.array([[25, 16]])
d2 = np.array([[11, 2], [13, 4]])
d3 = np.array([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((d1, d2, d3), axis=0)
print("\n Concat arrays into newArray\n", newArray)

# Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print("\nsortedarray...\n", sortedArray)

#Reshape the 'sortedArray' array, into 'reshapedArray',2 dimensions with a size of 2, 3.

reshapedArray = sortedArray.reshape(2,2,3)
print("\nreshaped Array...\n", reshapedArray)

#Unpack the array tuples from the above 'reshapedArray' into 4 well named variables.

reshapeedArrayB = reshapedArray.reshape(4,3)
print("\nsecond reshape...\n")
z,y,x,w = reshapeedArrayB


print(z)
print(y)
print(x)
print(w)


In [1]:
#Combined and sort the following arrays into one called 'comboArray' ...
import numpy as np

one = ([10, 11, 12, 13, 14, 15, 16, 17])
two = ([20, 21, 22, 23, 24, 25, 26, 27])
three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

comboArray = np.sort(np.concatenate((one, two, three)))
print("\ncomboArray\n", comboArray)

#Take 'comboArray' and perform the following slicing activities:

#print sec1 - the 2nd element
print(comboArray[1])
#print sec2 - all elements from the 3rd element to the last
print(comboArray[2:])
#print sec3 - all elements from the 4th to the 14th elements
print(comboArray[3:13])
#print sec4 - the last 6 elements
print(comboArray[-6:])
#print sec5 - all element from 
#0 up to and including 
#15, using the negative number method, i.e. taking a section from the end
print(comboArray[:-10]) 
#print sec6 - from #20 every even element to the end
print(comboArray[16::2])
#print sec7 - from the last element moving forward, every 5th element.
print(comboArray[-1::-5])



comboArray
 [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
1
[ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
[ 3  4  5  6  7 10 11 12 13 14]
[22 23 24 25 26 27]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
[20 22 24 26]
[27 22 15 10  3]


In [ ]:
#Using simple math operations, 
#broadcast the addition (+), division (/), and multiplication (*) operations for these 2 arrays --

g1 =np.array([[[ 0.0,  0.0,  0.10], [10.0, 10.30, 10.01]],
        [[20.0, 20.02, 20.10], [30.0, 31.0, 30.30]],
        [[40.40, 24.0, 40.0], [15.0, 15.5, 25.5]]])

g2 =np.array([[17.0, 70.0, 10.7]])

print(g1 + g2)
print(g1 / g2)
print(g1 * g2)

#Use the NumPy Arithmetic functions to do the subtraction of the above two arrays in point #7.

print(np.subtract(g1, g2))

#Using modulo find all elements that are divisible by 3 
# from the multi-dimensional array under point #7 above.

print(g1[g1 % 3 == 0])


In [27]:
#Using Series, create a DataFrame that looks like this:

#Ingredients	Quantity	Unit
#Flour	4	cups
#Milk	1	cup
#Eggs	2	large
#Spam	1	can
#Name: Dinner, dtype: object

import pandas as pd

Ingredients = pd.Series(["Flour", "Milk", "Eggs", "Spam"], name="Ingredients")
Quantity = pd.Series(["4", "1", "2", "1"], name ="Quantity")
Unit = pd.Series(["cups", "cup", "large", "can"], name="Unit")

Dinner = pd.concat([Ingredients, Quantity, Unit], axis=1)


print(Dinner)


  Ingredients Quantity   Unit
0       Flour        4   cups
1        Milk        1    cup
2        Eggs        2  large
3        Spam        1    can


In [35]:
# Take this data and create a DataFrame named studentData
import pandas as pd

data =    {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
         'Height': [5.1, 6.2, 5.1, 5.2],
         'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
         'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
         'Age': [21, 23, 24, 21],
         'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
         'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
     }
 
studentData = pd.DataFrame(data)
print(studentData)


# Add a new column to the DataFrame with the following deserts:
# ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]

studentData.insert(3, "deserts", ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"],True)
print("\nstudentdata desserts\n", studentData)

# Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"
studentData.sort_values(by = ["Name", "address"], inplace=True)
print('\n studentData sorted by column and address\n', studentData)


      Name  Height Qualification  address  Age        Pets           sport
0      Jai     5.1           Msc    Delhi   21         Dog           Darts
1  janusha     6.2            MA     Doha   23       Bunny      Basketball
2   Gaurav     5.1           Msc  Chennai   24  Chinchilla  PaddleBoarding
3     Anuj     5.2           Msc   Dakhar   21      Parrot         Cricket

studentdata desserts
       Name  Height Qualification       deserts  address  Age        Pets  \
0      Jai     5.1           Msc     ice cream    Delhi   21         Dog   
1  janusha     6.2            MA  Cashew Fudge     Doha   23       Bunny   
2   Gaurav     5.1           Msc       waffels  Chennai   24  Chinchilla   
3     Anuj     5.2           Msc  Carrot Halwa   Dakhar   21      Parrot   

            sport  
0           Darts  
1      Basketball  
2  PaddleBoarding  
3         Cricket  

 studentData sorted by column and address
       Name  Height Qualification       deserts  address  Age        Pets  \
3

In [12]:
#Save this DataFrame here below to disc as a .CSV file with the name cows_and_goats.csv:
import pandas as pd 

df = pd.DataFrame({"Cows": [12, 20], "Goats": [22, 19]}, index=["Year 1", "Year 2"])
df
df.to_csv("cows_and_goats.csv")
 







In [13]:
#(A) Using Pandas, make your own .CSV file with data on vegetables and save it. 
import pandas as pd

veggies = pd.DataFrame({"Vegetable": ["Kale", "Cucumber", "Onions"], 
                        "Shelf_Life": ["2 Weeks", "1 Week", "3 weeks"]})

print(veggies)

veggies.to_csv('veggies.csv', index=False)

df = pd.read_csv('veggies.csv')
print(df)


  Vegetable Shelf_Life
0      Kale    2 Weeks
1  Cucumber     1 Week
2    Onions    3 weeks
  Vegetable Shelf_Life
0      Kale    2 Weeks
1  Cucumber     1 Week
2    Onions    3 weeks


In [16]:
#(B) Using Pandas, make a change to your CSV file, and save a copy with a different name.
import pandas as pd

df = pd.read_csv('veggies.csv')

print(df)

veggies2 =df.replace(to_replace=["3 weeks"], value= "4 Weeks")

veggies2.to_csv('veggies2')

print(veggies2)

  Vegetable Shelf_Life
0      Kale    2 Weeks
1  Cucumber     1 Week
2    Onions    3 weeks
  Vegetable Shelf_Life
0      Kale    2 Weeks
1  Cucumber     1 Week
2    Onions    4 Weeks
